### PR TITLE
JS fixes

### PR DESCRIPTION
**Pull request by buu700**
1. Changed the local variable crypto to Crypto; because Haxe emits JS in strict mode, as written this had been setting crypto to undefined before trying to use it.

2. Not a "fix" per se since haxe.io.Bytes internally converts ints to uints anyway, but it seems more idiomatic to use a Uint8Array rather than an Int8Array here.

### CODE REVIEW

**Comment by buu700** [comment]
On a related note, your call of course, but my understanding is that /dev/urandom is pretty much always preferred to /dev/random.

**Comment by soywiz** [comment]
Thanks. Going to change the `/dev/urandom` part. It is always available? O should I check existence?

**Comment by buu700** [comment]
Thanks for the quick merge!

I'm not aware offhand of any instance in which /dev/random might exist where /dev/urandom doesn't, but as a sanity check I just did a quick google and confirmed that at least in FreeBSD they both appeared at the same time (July 1996); so it seems like there'd be no benefit to checking for both. Also, related informative post from @tqbf with a citation from djb: http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers

**Comment by fulopm** [comment]
/dev/random and /dev/urandom are both available on almost all linux distros. The only difference is that /dev/random is blocking (terminates the process while enough random bytes are not available), and /dev/urandom is not.

**Pull request merged**
